<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
   <?php echo $this->headTitle('LoudBite.com – Update Info'); ?>
</head>
<body>

<?php echo $this->render('includes/header.phtml') ?>


   <h3>Update My Profile</h3>
   <form action="saveprofile" method="POST">
   <table width="500" border="0">
   <tr>
      <td>Username: </td>
      <td><input type="text" name="username"
          value="<?php echo $this->username?>" /></td>
   </tr>
   <tr>
      <td>Email: </td>
      <td><input type="text" name="email"
          value="<?php echo $this->email?>" /></td>
   </tr>
   <tr>
      <td>Password: </td>
      <td><input type="password" name="password"
          value="<?php echo $this->password?>" /></td>
   </tr>
   <tr>
      <td colspan="2">
        <input type="submit" value=" Update my account! " />
      </td>
   </tr>
   </table>
   </form>
</body>
</html>
