<?php echo $this->doctype('XHTML1_STRICT'); ?> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">  
<head>
<?php echo $this->headTitle('LoudBite.com - News &amp; Info '); ?>

  </head>
  <body>

<?php echo $this->render('includes/header.phtml') ?>

    <h3>News and Info</h3>
    <table>
      <tr><td>Artist name goes here</td></tr>
      <tr><td>News items will go here</td></tr>
      <tr><td>Items of interest</td></tr>
      <tr><td>Pictures</td></tr>
    </table>
  </body>
</html>
